Update localstack domain
resource-watch/api-infrastructure pull request #120
Opened 2024-12-03 10:30 UTC by solomon-negusse

2024-12-03 22:24 UTC, gtempus requested changes
I did get this up and running, @solomon-negusse. 🎉 
However, I need to get a microservice successfully stood up to try it out. Let's get `gfw-area` when you have a chance tomorrow. 🙏

2024-12-03 22:24 UTC, gtempus commented on terraform-localstack/README.md
> +2 - Terraform apply the content of this folder and confirm the changes in the prompt (use terraform version `v1.3.6`). This will output an `access_url` of the form `http://host.docker.internal:4566/r
I did get this access url. But the logs give me this warning:
`localstack.deprecations    : /restapis/<api_id>/<stage>/_user_request_ is deprecated (since 3.8.0) and will be removed in upcoming releases of LocalStack! Use /_aws/execute-api/<api_id>/<stage> instead.`

Should we use that path instead?

2024-12-04 10:29 UTC, solomon-negusse commented on terraform-localstack/README.md
> +2 - Terraform apply the content of this folder and confirm the changes in the prompt (use terraform version `v1.3.6`). This will output an `access_url` of the form `http://host.docker.internal:4566/r
Done. Hit this issue: https://github.com/localstack/localstack/issues/10461 using that endpoint though as the `localstack/localstack` image we use doesn't have the fix so pinning to a later image version (`localstack/localstack:4.0.3`) with the fix.

2024-12-04 12:21 UTC, gtempus approved these changes
Great. Glad that worked out.

FYI, I used `tfenv` to manage my terraform version. Is that what you use?

2024-12-04 12:30 UTC, solomon-negusse commented
> Great. Glad that worked out.
> 
> FYI, I used `tfenv` to manage my terraform version. Is that what you use?

Yup, makes life easier.

2024-12-04 18:40 UTC, merged