Feature/postgresql
resource-watch/api-infrastructure pull request #33
Opened 2020-09-18 15:17 UTC by thomas-maschler

Add Aurora PostgreSQL database

2020-09-22 09:47 UTC, tiagojsag requested changes

2020-09-22 09:47 UTC, tiagojsag commented on terraform/variables.tf
> +variable "backup_retention_period" {
IMO these variable names should reflect the fact that they concern Aurora

2020-09-22 09:47 UTC, tiagojsag commented on .github/workflows/terraform_build.yaml
> +        ./scripts/infra plan -var "rds_password=${RDS_PASSWORD}"
is this really needed? shouldn't this value already be available as an env var?

2020-09-22 09:47 UTC, tiagojsag commented on terraform/main.tf
> +  security_group_ids = [module.postgresql.security_group_id]
not really sure why this is needed. My approach so far has been to attach SGs to the private networks, so that all services can talk to each other on a private network, not accessible from the outside. We could create tighten this by using this 1-on-1 approach, but IMO that makes things unnecessarily harder to manage, with marginal benefits to security. If you decide to use this approach, I would suggest also allowing this SG on the bastion, so we can connect to Aurora from the outside.

2020-09-22 09:47 UTC, tiagojsag commented on terraform/modules/postgresql/main.tf
> +  engine_version                  = "11.7"
this should to be on the ignore list, IMO, otherwise upgrades done in the UI will cause TF to destroy and recreate aurora

2020-09-23 13:19 UTC, thomas-maschler commented on .github/workflows/terraform_build.yaml
> +        ./scripts/infra plan -var "rds_password=${RDS_PASSWORD}"
not in github workflow. We could switch to generating random passwords for aurora in TF. This way we wouldn't need to store it anywhere outside of AWS secret manager and TF state

2020-09-23 13:23 UTC, thomas-maschler commented on terraform/main.tf
> +  security_group_ids = [module.postgresql.security_group_id]
The approach here is to create a security group for db services and allow ingress and egress traffic on the db port within the security group.

I attached the sg to the DB, ECS cluster and the bastion host.

2020-09-23 13:24 UTC, thomas-maschler commented on terraform/modules/postgresql/main.tf
> +  engine_version                  = "11.7"
why would you do upgrade via the UI?

2020-09-23 13:29 UTC, tiagojsag commented on terraform/modules/postgresql/main.tf
> +  engine_version                  = "11.7"
I guess not, now that I think about it.

2020-09-23 13:31 UTC, tiagojsag approved these changes

2020-09-23 14:26 UTC, merged

2020-09-23 15:05 UTC, thomas-maschler commented on terraform/main.tf
> +  security_group_ids = [module.postgresql.security_group_id]
Adding a new SG to EKS cluster actually forces TF to recreate the cluster which is not what we want. I will hence allow ingress for the VPC CIDR block instead.