Get scaling config and cron schedule from vars
resource-watch/api-infrastructure pull request #52
Opened 2020-10-21 21:02 UTC by ethanroday

- Parameterize lambda module to provide scaling config based on variables in root config
- Add cron expressions for scaling at the right time of day
- Pass scaling config to lambda function through CW event rule input

NOTE: The cron configuration is currently set to upscale every 30 minutes and downscale every 30 minutes (offset by 15) for testing purposes only! Will change to correct config when going to staging/prod.

2020-10-22 14:24 UTC, tiagojsag approved these changes, later dismissed
There are a bunch of things here that I'm not familiar with, so maybe my review is not very valuable, but it seems good to me :+1:

2020-10-23 15:52 UTC, thomas-maschler requested changes
AWS creates a logging group for the lambda function implicitly. 
You will have to specify it in terraform. 
Since AWS already created it for you, you will first have to delete the log group via the console before you deploy your new code. Otherwise there will be a conflict.

I would also rename the module name to something close to what is does ("cloud watch events" if you plan to add additional events here or "eks auto scaler" if you plan to only use it for this one feature)

```
resource "aws_cloudwatch_log_group" "lambda" {
  name              = "/aws/lambda/eks_scaling" // verify log group name
  retention_in_days = var.log_retention
}
```

2020-10-23 15:52 UTC, thomas-maschler commented on lambda/eks_scaling/src/eks_scaling.py
> +    # }
I would slightly change the payload structure to make it more scalable:

```json
[{
	"eks_cluster_name": "cluster-name",
	"node_groups": [{
			"node_group_name": "apps-node-group",
			"scaling_config": {
				"minSize": 123,
				"maxSize": 123,
				"desiredSize": 123
			}
		},
		{
			"node_group_name": "gfw-node-group",
			"scaling_config": {
				"minSize": 123,
				"maxSize": 123,
				"desiredSize": 123
			}
		}
	]
}]
```

2020-10-23 16:13 UTC, ethanroday commented on lambda/eks_scaling/src/eks_scaling.py
> +    # }
Sounds reasonable to me. Fixed.

2020-10-23 16:14 UTC, ethanroday commented
Added log group explicitly and deleted the existing one in the console.

2020-10-23 16:23 UTC, thomas-maschler requested changes
Looks good.
One last thing. I assume the scaling logic will vary across environments, correct?
In that case I would not set default values for the variables, but instead set them in 

`vars/terraform-dev/tfvars`
`vars/terraform-staging/tfvars`
`vars/terraform-production/tfvars`

accordingly

2020-10-23 16:25 UTC, ethanroday commented
Thanks for bringing that up - was actually going to ask how that would work when going to staging. I'll move the configs - just a minute.

2020-10-23 16:31 UTC, ethanroday commented
Okay done. For now I've just put _all_ of the scaling config for `apps-node-group` and `gfw-node-group` into the `.tfvars` file, since we may want to vary the base configs by environment as well.

2020-10-23 16:31 UTC, ethanroday commented
Oops...plan is failing now.

2020-10-23 16:32 UTC, thomas-maschler commented
You still need to declare the variables in `variables.tf` just leave out the default value.
Set the value in the tfvar files

2020-10-23 16:33 UTC, ethanroday commented
Fixed. I left the default value as the same as the downscaled value just in case they ever get deleted accidentally in tfvars.

2020-10-23 16:35 UTC, thomas-maschler commented
It would then prompt you to provide a value during plan

From: Ethan Roday <notifications@github.com>
Date: Friday, October 23, 2020 at 12:33 PM
To: resource-watch/api-infrastructure <api-infrastructure@noreply.github.com>
Cc: Thomas Maschler <Thomas.Maschler@wri.org>, Review requested <review_requested@noreply.github.com>
Subject: Re: [resource-watch/api-infrastructure] Get scaling config and cron schedule from vars (#52)

Fixed. I left the default value as the same as the downscaled value just in case they ever get deleted accidentally in tfvars.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/resource-watch/api-infrastructure/pull/52#issuecomment-715448091>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABZQNIKI3EHXZKWI6WON4M3SMGV7LANCNFSM4S2JVEDQ>.

2020-10-23 16:35 UTC, thomas-maschler approved these changes

2020-10-23 16:36 UTC, merged