Change EKS instance types from m5a.large to c5a.xlarge
resource-watch/api-infrastructure pull request #72
Opened 2020-11-30 17:50 UTC by ethanroday

Change EKS instance types from m5a.large to c5a.xlarge on recommendation from @tiagojsag and @ikas. Sounds like we should have switched to c5a.xlarge in the first place, but I got confused with a recommendation from AWS and switched to the wrong instance type.

2020-11-30 17:57 UTC, thomas-maschler requested changes
In `modules/node_group/main.tf` please add `create_before_destroy = true` to node group lifecycle to avoid downtime during recreation

2020-12-01 15:51 UTC, ethanroday commented
> 
> 
> In `modules/node_group/main.tf` please add `create_before_destroy = true` to node group lifecycle to avoid downtime during recreation

Done.

@tiagojsag when making this change I noticed the following line that was added by you 8 months ago: 

    ignore_changes        = [scaling_config[0].desired_size]

Could this be why the desired size of the node groups in production didn't match the config? Do you know why this was added?

2020-12-01 15:53 UTC, tiagojsag commented
If I recall correctly, the desired size was being modified by the cluster's autoscaler based on the actual pods living there. Every time we deployed TF, it would override the autoscaler's value, which would probably eventually re-override it again as it went about doing its job.

2020-12-01 15:53 UTC, tiagojsag approved these changes

2020-12-01 22:06 UTC, thomas-maschler approved these changes

2020-12-02 17:31 UTC, merged