Change eks instance types in staging
resource-watch/api-infrastructure pull request #74
Opened 2020-12-10 17:12 UTC by ethanroday

2020-12-10 21:40 UTC, thomas-maschler requested changes

2020-12-10 21:40 UTC, thomas-maschler commented on terraform/modules/node_group/main.tf
> +  node_group_name = "${var.node_group_name}-${var.instance_types}"
```suggestion
  node_group_name = replace("${var.node_group_name}-${var.instance_types}", ".", "_")
```

2020-12-11 05:48 UTC, tiagojsag submitted a review, later dismissed

2020-12-15 17:22 UTC, ethanroday commented
@thomas-maschler sorry for the delay on this - approved your suggestion

2023-01-02 09:27 UTC, closed without merging